- name: Run autopost script
  env:
    FTP_SERVER: ${{ secrets.FTP_SERVER }}
    FTP_USER: ${{ secrets.FTP_USER }}
    FTP_PASS: ${{ secrets.FTP_PASS }}
    EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
    EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
  run: |
    python autopost.py
